---
version: "3.7"

services:
  redis:
    image: redis/redis-stack:6.2.6-v7-x86_64
    container_name: redis
    restart: always
    volumes:
      - redis:/data
    ports:
      - 6379:6379
      - 8001:8001
    labels:
      - VIRTUAL_PORT=8001
volumes:
  redis: {}
